export { Layout as PageLayout } from "./Layout"
export { Home as PageHome } from "./Home"
export { Explorar as PageExplorar } from "./Explorar"
export { Grifinoria as PageGrifinoria } from "./Grifinoria"
export { Sonserina as PageSonserina } from "./Sonserina"